name: animation_model
description: |
  AnimationModel is a pure dart package to animate multiple values at the same time
  using the Breakpoint objects which is a linked list object
version: 1.0.0
repository: https://github.com/Davenchy/animation_model

environment:
  sdk: ">=2.18.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
